title: ThinkNote
subtitle: Keep thinking
link: 
meta:
  description: 记录一些关于内核,驱动,WIFI和WEB的相关知识
  keywords: !!seq
    - linux
    - driver
    - wifi
  author: limatrix
master:
  name: limatrix
  about: 
  email: 
rss:
  title: RSS feed title
  desc: RSS feed description
  lang: zh-cn
  max: 10
copyright:
  owner: limatrix
  beginYear: 2016
  endYear: 2017
theme: default
codetheme: night
